-- return {
--   {
--     "Exafunction/codeium.nvim",
--     events = { "InsertEnter" },
--     -- lazy = false,
--     enabled = false,
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       -- "hrsh7th/nvim-cmp",
--     },
--     lazy = false,
--     -- config = function() require("codeium").setup {} end,
--     config = function()
--       require("codeium").setup({
--         -- panel = {
--         --   enabled = true,
--         -- },
--         -- suggestion = {
--         --   enabled = true,
--         --   auto_trigger = true,
--         --   debounce = 75,
--         --   keymap = {
--         --     accept = "<C-g>",
--         --     next = "<C-.>",
--         --     prev = "<C-,>",
--         --     dismiss = "<C-x>",
--         --   },
--         -- },
--       })
--       -- local api_key = os.getenv("CODESTATS_API_KEY") or ""
--       -- require("codeium.vim").setup({
--       --   api_key = api_key,
--       -- })
--       vim.g.codeium_disable_bindings = 1
--       vim.keymap.set("i", "<c-g>", function()
--         return vim.fn["codeium#Accept"]()
--       end, { expr = true })
--       -- nvim_set_keymap("i", "<C-g>", "v:lua.codeium#Accept()", { expr = true })
--       -- vim.keymap.set("i", "<C-g>", function()
--       -- return vim.fn["codeium#Accept"]()
--       -- end, { expr = true })
--       -- vim.keymap.set("i", "<c-.>", function()
--       --   return vim.fn["codeium#CycleCompletions"](1)
--       -- end, { expr = true })
--       -- vim.keymap.set("i", "<c-,>", function()
--       --   return vim.fn["codeium#CycleCompletions"](-1)
--       -- end, { expr = true })
--       vim.keymap.set("i", "<c-x>", function()
--         return vim.fn["codeium#Clear"]()
--       end, { expr = true })
--     end,
--   },
-- }
