return {}
-- return {
--   {
--     "epwalsh/obsidian.nvim",
--     -- tag = "*",
--     lazy = true,
--     ft = { "markdown", "quarto" },
--     dependencies = {
--       -- Required.
--       "nvim-lua/plenary.nvim",
--     },
--     opts = {
--       workspaces = {
--         -- {
--         --   name = "personal",
--         --   path = "~/Obsidian/Notes",
--         -- },
--         {
--           name = "no-vault",
--           path = function()
--             -- alternatively use the CWD:
--             -- return assert(vim.fn.getcwd())
--             return assert(vim.fs.dirname(vim.api.nvim_buf_get_name(0)))
--           end,
--           overrides = {
--             notes_subdir = vim.NIL, -- have to use 'vim.NIL' instead of 'nil'
--             new_notes_location = "current_dir",
--             templates = {
--               subdir = vim.NIL,
--             },
--             disable_frontmatter = true,
--           },
--         },
--       },
--       -- Optional, if you keep notes in a specific subdirectory of your vault.
--       -- notes_subdir = "notes",
--       -- Optional, set the log level for obsidian.nvim. This is an integer corresponding to one of the
--       -- log levels defined by "vim.log.levels.*".
--       log_level = vim.log.levels.INFO,
--       -- Optional, configure additional syntax highlighting / extmarks.
--       -- This requires you have `conceallevel` set to 1 or 2. See `:help conceallevel` for more details.
--       ui = {
--         enable = false, -- set to false to disable all additional syntax features
--         update_debounce = 200, -- update delay after a text change (in milliseconds)
--         -- Define how various check-boxes are displayed
--         checkboxes = {
--           -- NOTE: the 'char' value has to be a single character, and the highlight groups are defined below.
--           [" "] = { char = "󰄱 ", hl_group = "ObsidianTodo" },
--           ["x"] = { char = " ", hl_group = "ObsidianDone" },
--           [">"] = { char = " ", hl_group = "ObsidianRightArrow" },
--           ["~"] = { char = "󰰱 ", hl_group = "ObsidianTilde" },
--           -- Replace the above with this if you don't have a patched font:
--           -- [" "] = { char = "☐", hl_group = "ObsidianTodo" },
--           -- ["x"] = { char = "✔", hl_group = "ObsidianDone" },
--           -- You can also add more custom ones...
--         },
--         -- Use bullet marks for non-checkbox lists.
--         bullets = { char = "•", hl_group = "ObsidianBullet" },
--         external_link_icon = { char = " ", hl_group = "ObsidianExtLinkIcon" },
--         -- Replace the above with this if you don't have a patched font:
--         -- external_link_icon = { char = "", hl_group = "ObsidianExtLinkIcon" },
--         reference_text = { hl_group = "ObsidianRefText" },
--         highlight_text = { hl_group = "ObsidianHighlightText" },
--         tags = { hl_group = "ObsidianTag" },
--         hl_groups = {
--           -- The options are passed directly to `vim.api.nvim_set_hl()`. See `:help nvim_set_hl`.
--           ObsidianTodo = { bold = true, fg = "#838383" },
--           ObsidianDone = { bold = true, fg = "#36CE5E" },
--           ObsidianRightArrow = { bold = true, fg = "#f78c6c" },
--           ObsidianTilde = { bold = true, fg = "#ff5370" },
--           ObsidianBullet = { bold = true, fg = "#89ddff" },
--           ObsidianRefText = { underline = true, fg = "#c792ea" },
--           ObsidianExtLinkIcon = { fg = "#c792ea" },
--           ObsidianTag = { italic = true, fg = "#89ddff" },
--           ObsidianHighlightText = { bg = "#75662e" },
--         },
--       },
--     },
--   },
-- }
